### ISSUE TITLE
outdated preprocess file

### ISSUE THREAD

**Issue by k47ha** [CogSciUOS/asparagus#56]
https://github.com/CogSciUOS/asparagus/blob/66b8354037eb31e290c4680c213b79ea75b01cac/code/preprocessor.py#L187

This file is old, right?
We do not use it anymore?
The newer and correct ones are in the folder code/preprocess?

If all is answered yes, i will delete this file.

**Comment by sophiasw** [comment]
ja das ist die Version die Thomas und ich am Anfang geschrieben haben

**Comment by k47ha** [comment]
Danke!
